[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
bbs = { path = "../bbs" }

[dev-dependencies]
reqwest = "0.11.18"
