application:
  port: 8000
  host: 0.0.0.0
  hmac_secret: "3406a6967e40bf9e1540ead5a3b2eff19b41966131abc09233fd3a6bdbd9faca"
database:
  host: "127.0.0.1"
  port: 8090
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: false
email_client:
  base_url: "localhost"
  sender_email: "sender@example.com"
  authorization_token: "my-secret-token"
  timeout_milliseconds: 10000
redis_uri: "redis://127.0.0.1:6379"
